grammar uibk.safesec.AttackTree with uni.ulm.safesec.Util 

generate attackTree "http://www.safesec.uibk/AttackTree"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore


@Override 
Model:
	attackTreeModel+=AttackTreeModel*
;

AttackTreeModel:
	AttackTarget|AttackTreeElement
;

AttackTreeElement:
	AttackStep|SubTree
;
//TODO: Validation id xor cpe 
AttackTarget:
         "AttackTarget" (('id''='name=ID)? & ("CPE" "=" cpe=CPE)? & ("synonyms" "=" synonyms=Synonyms)? & ("CWE" "=" cwe=CWE)? &  
         	("CVSS" "=" cvss=CVSSVECTORList)? & ("note" "=" note=STRING)? & (("BaseScore" "=" baseScore=ScoreList)?) & 
         	(("ImpactScore" "=" impactScore=ScoreList)?) & (("ExploitabilityScore" "=" exploitabilityScore=ScoreList)?) )
         	"{" attackTree=AttackTree "}"
;

CVSSVECTORList:
     '[' cvssList+=CVSSVECTOR (',' cvssList+=CVSSVECTOR)* ']'
;

ScoreList:
     '[' score+=REAL (',' score+=REAL)* ']'
;

SubTree:
	gate=Gate (name=ID)?  ("note" "=" note=STRING)?  "{" attackTree+=AttackTree (','attackTree+=AttackTree)* "}" 
;

Gate: 
	 name='AND'| name='OR'|name='SAND'|name='PAND'|name='SOR'|name='FDEP' 'trigger' '='trigger=AttackTree |name='SPARE' 'primaryBasicEvent' '='primary=AttackTree| name='VOT' 'numberOfDisrubtions' '=' numberOfDisrubtions=INT 
;

AttackStep: 
	"AttackStep" (name=ID)? (("description" "=" description=STRING) & (("CVE""="cve=CVE)?) & (("CVSS" "=" cvss=CVSSVECTOR)?) & 
		(("probability""="probability=REAL)?) & (("BaseScore" "=" baseScore=REAL)?) & (("ImpactScore" "=" impactScore=REAL)?) &
		 (("ExploitabilityScore" "=" exploitabilityScore=REAL)?)& (("epss" "=" epss=REAL)?)&(("note" "=" note=STRING)?)
	) //("{" attackTree=AttackTree "}")?
;

AttackTreeSubElements:
	AttackStep|SubTree
;

AttackTree:
	step=AttackStep| subTree=SubTree | ref=[AttackTreeSubElements]
;

Synonyms:
	"(" STRING ("," STRING)* ")"
;
